INSERT INTO job_applied
           (job_id,
            application_sent_date,
            Custom_resume,
            resume_file_name,
            Cover_letter_sent,
            cover_letter_file_name,
            status)
VALUES      (1,
            '2024-02-01',
            'true',
            'resume_01.pdf',
            'true',
            'cover_letter_01.pdf',
            'submitted'),
            (2,
            '2024-05-01',
            'false',
            'resume_02.pdf',
            'false',
            'NULL',
            'interview scheduled'),
            (3,
            '2024-06-01',
            'true',
            'resume_03.pdf',
            'true',
            'cover_letter_03.pdf',
            'ghosted'),
            (4,
            '2024-08-01',
            'true',
            'resume_04.pdf',
            'False',
            'NULL',
            'submitted'),
            (5,
            '2024-05-01',
            'false',
            'resume_05.pdf',
            'true',
            'cover_letter_05.pdf',
            'rejected');

SELECT *
FROM job_applied